### PR TITLE
Visual

### PR DESCRIPTION
**Pull request by Rachella**

### CODE REVIEW

**Comment by h8rry** [comment]
**+37,606** lines of additions..

**Comment by h8rry** [comment]
No need to include `splash.ai`, right? and `.ai` in general.

**Comment by Rachella** [comment]
No it's not... They are pictures... I thought... I looked...

**Comment by h8rry** [comment]
Yo the rest looks fine

**Comment by Rachella** [comment]
Yeah, it's not really 30K+ lines.. it's the pictures.. I think? 

The ai file is what CLI used to convert the images, I'll see if it is still needed.

**Pull request merged**
